### PR TITLE
Add some new malware

### PR DESCRIPTION
**Pull request by iam-py-test**
This adds one trojan, a PUP, and some kind of scam-ware.
VT detentions: 
https://www.virustotal.com/gui/file/a367e0562e612bc66729f3a4676bad849e5c3c32fad8223b5ea991e11604f5fe
https://www.virustotal.com/gui/file/5cb30adb8f800bd31c6e4c261f2c9cc4cc14906e9c238b92c6233aba4e925f02
https://www.virustotal.com/gui/file/1f009cfd83f457f5f9b9820f7225ad87d16097b825fba7c4efedaf0d18cb5082

### CODE REVIEW

**Comment by iam-py-test** [comment]
@donno2048 any updates?

**Comment by donno2048** [comment]
Please provide additional details for me to review these files:
1. What is the impact of the malware
2. How to execute the vulnerability
3. etc.

**Comment by iam-py-test** [comment]
> Please provide additional details for me to review these files:
> 
>     1. What is the impact of the malware
> 
>     2. How to execute the vulnerability
> 
>     3. etc.

I will get back to you later today or tomorrow.

**Comment by iam-py-test** [comment]
@donno2048 sorry for the delay.
What are the criteria for files being added to this repo?

**Comment by donno2048** [comment]
Not much of criteria as long as it is simple to "run" them and the effect is irreversible

**Comment by iam-py-test** [comment]
> Not much of criteria as long as it is simple to "run" them and the effect is irreversible

Ah, then these might now fit that. Let me open a new PR with newer samples

**Pull request closed without merging**
